# This file was generated by GoReleaser. DO NOT EDIT.
cask "masume" do
  version "0.0.14"

  on_macos do
    on_arm do
      sha256 "4e6f54e8b39057e49480905a71a24d8265c9811f303916089bf3834df35f420c"
      url "https://github.com/masumedb/masume/releases/download/v#{version}/masume_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b13d4318d9047c1376c354a8c522cae2ee89c02b47b35134f48bd3ca431a8c0b"
      url "https://github.com/masumedb/masume/releases/download/v#{version}/masume_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1846cc74db260ac7225e922e79ffbb9f352d81164e70a6f20a5e32334f4d7300"
      url "https://github.com/masumedb/masume/releases/download/v#{version}/masume_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c17c48e96fe93997928e27915f90a55a390a9346a4ce3b28af1ca503c75624fb"
      url "https://github.com/masumedb/masume/releases/download/v#{version}/masume_#{version}_linux_amd64.tar.gz"
    end
  end

  name "masume"
  desc "Database client for the terminal"
  homepage "https://github.com/masumedb/masume"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "masume"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/masume"]
    end
  end

  # No zap stanza required
end
