# This file was generated by GoReleaser. DO NOT EDIT.
cask "masume" do
  version "0.0.10"

  on_macos do
    on_arm do
      sha256 "15776aa7a003604634ae8180c722c58201a7660bbf1753478635ccbff0e83f16"
      url "https://github.com/masumedb/masume/releases/download/v#{version}/masume_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d05d4b61c2339d801ff1711b29ec062835f4c5db586745979832f7f5b626b456"
      url "https://github.com/masumedb/masume/releases/download/v#{version}/masume_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f23f8cc5f592deea71e9f05d01f81249ca2e15472617fea094d24c4ac57b2216"
      url "https://github.com/masumedb/masume/releases/download/v#{version}/masume_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5d6ff9be352796a59cbba068978d9bdc442c7423aae385f73775f25ad4170e86"
      url "https://github.com/masumedb/masume/releases/download/v#{version}/masume_#{version}_linux_amd64.tar.gz"
    end
  end

  name "masume"
  desc "Database client for the terminal"
  homepage "https://github.com/masumedb/masume"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "masume"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/masume"]
    end
  end

  # No zap stanza required
end
