# This file was generated by GoReleaser. DO NOT EDIT.
cask "masume" do
  version "0.0.12"

  on_macos do
    on_arm do
      sha256 "e8d6c6bab6954fec432a31d0d7648990321c654c5b94be969bed345455b0a299"
      url "https://github.com/masumedb/masume/releases/download/v#{version}/masume_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "31b5858d82e9dff4f663849c1f5524b392f583013be60013dd0766613504c558"
      url "https://github.com/masumedb/masume/releases/download/v#{version}/masume_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f3b765568caef68c173ec6eb5c64277cb075d60ed491b166514dcdf1280a74e7"
      url "https://github.com/masumedb/masume/releases/download/v#{version}/masume_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "56c14231e52bfbde905f8259280681faa5279d2e2c39ecc8583b777f9ef612ae"
      url "https://github.com/masumedb/masume/releases/download/v#{version}/masume_#{version}_linux_amd64.tar.gz"
    end
  end

  name "masume"
  desc "Database client for the terminal"
  homepage "https://github.com/masumedb/masume"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "masume"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/masume"]
    end
  end

  # No zap stanza required
end
